### ISSUE TITLE
Jalali day is out of valid range.

### ISSUE THREAD

**Issue by tazik561** [FatulM/shamsi_date#10]
Hi, I am trying to get session by this command:
`Jalali.now().copy(month: 12).formatter.mN`

But I got This error :

```
 Jalali.now().copy(month: 12).formatter.mN
Unhandled exception:
DateException: Jalali day is out of valid range.
#0      new Jalali (package:shamsi_date/src/jalali/jalali_date.dart:129:9)
#1      Jalali.copy (package:shamsi_date/src/jalali/jalali_date.dart:222:14)
#2      MonthPickerModel.Eval ()
#3  
```
I expect that I get اسفند . 

I am using `shamsi_date: ^0.9.1`   version and this is my doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.5, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] VS Code (version 1.56.2)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.
```

**Comment by FatulM** [comment]
Hi,
can you please provide me the time which you executed this command ?

I think the problem is that you are in the last day of month
and when you copy date to month 12
when you are in a leap year
it will crash

since Jalali(1400,12,30) is not valid

you can switch day to for example 1 to avoid this:
```Jalali.now().copy(month: 12, day: 1).formatter.mN```

and a better approach would be to not use `now()` when not needed
```Jalali(1400, 12, 1).formatter.mN```

always dates must be valid
otherwise shamsi_date will throw exception

And also as a recommendation I personally prefer to use `withDay`, `withMonth`, `withYear`
over `copy` when you are changing only one variable
```Jalali.now().withDay(1).withMonth(12).formatter.mN```
but here `copy` seems better.

please check and inform me if the error occurs again

@tazik561

**Comment by tazik561** [comment]
I try to get session name so in order to  I generate a list and I pass list index to my method :

```
months = List.generate(12, (index) {
....
getMonthNameByIndex(index + 1)
```

This is `getMonthNameByIndex` method:
```
  @override
  String getMonthNameByIndex(int monthIndex) {
    finalMonth = Jalali.now().withMonth(index); // I used withMonth as you suggestion
    return finalMonth;
  }
```
But when index is 12 I got `DateException: Jalali day is out of valid range.`

**Comment by FatulM** [comment]
I think you didn't read my comment completely! :D

**Comment by FatulM** [comment]
check this
@tazik561

 ```dart
@override
  String getMonthNameByIndex(int monthIndex) {
    finalMonth = Jalali.now().withDay(1).withMonth(index); // I used withMonth as you suggestion
    return finalMonth;
  }
```

this will work i persume!

**Comment by tazik561** [comment]
> ```
>  String getMonthNameByIndex(int monthIndex) {
>    finalMonth = Jalali.now().withDay(1).withMonth(index); // I used withMonth as you suggestion
>    return finalMonth;
>  }```
>  this will work i persume!
> ```

Yes, I today is last day of month and I add .withDay(1) and the problem gone. thanks bro.

**Comment by FatulM** [comment]
Your welcome!
😄

**Comment by FatulM** [comment]
dates should always be valid, otherwise it throws
